CREATE TABLE august2020 (
    `Column_1` VARCHAR(12) CHARACTER SET utf8,
    `Column_2` VARCHAR(12) CHARACTER SET utf8,
    `Column_3` VARCHAR(9) CHARACTER SET utf8,
    `Column_4` VARCHAR(10) CHARACTER SET utf8,
    `Column_5` VARCHAR(10) CHARACTER SET utf8,
    `Column_6` VARCHAR(10) CHARACTER SET utf8,
    `Column_7` VARCHAR(10) CHARACTER SET utf8,
    `Column_8` VARCHAR(12) CHARACTER SET utf8,
    `Column_9` VARCHAR(12) CHARACTER SET utf8,
    `Column_10` VARCHAR(10) CHARACTER SET utf8,
    `Column_11` VARCHAR(10) CHARACTER SET utf8,
    `Column_12` VARCHAR(10) CHARACTER SET utf8,
    `Column_13` VARCHAR(8) CHARACTER SET utf8,
    `Column_14` VARCHAR(10) CHARACTER SET utf8,
    `Column_15` VARCHAR(10) CHARACTER SET utf8,
    `Column_16` VARCHAR(10) CHARACTER SET utf8,
    `Column_17` VARCHAR(12) CHARACTER SET utf8,
    `Column_18` VARCHAR(12) CHARACTER SET utf8,
    `Column_19` VARCHAR(10) CHARACTER SET utf8,
    `Column_20` VARCHAR(12) CHARACTER SET utf8,
    `Column_21` VARCHAR(12) CHARACTER SET utf8,
    `Column_22` VARCHAR(12) CHARACTER SET utf8,
    `Column_23` VARCHAR(12) CHARACTER SET utf8,
    `Column_24` VARCHAR(10) CHARACTER SET utf8,
    `Column_25` VARCHAR(10) CHARACTER SET utf8,
    `Column_26` VARCHAR(12) CHARACTER SET utf8,
    `Column_27` VARCHAR(10) CHARACTER SET utf8,
    `Column_28` VARCHAR(10) CHARACTER SET utf8,
    `Column_29` VARCHAR(12) CHARACTER SET utf8,
    `Column_30` VARCHAR(10) CHARACTER SET utf8,
    `Column_31` VARCHAR(12) CHARACTER SET utf8
);
INSERT INTO august2020 VALUES
    ('Gratson','Pettengill','Bork','Otero','Hutchinson','Hutchinson','Turner','Ortiz','Ortiz','Almquist','Ortiz','Joseph','Swor','Richardson','Hang','Hang','Barish','Bork','Almquist','Linovitz','Shah','Todd','Todd','Nguyen','Joseph','Barish','Fadi','Richardson','Anderson','Nguyen','Ortiz'),
    ('Walters','Gratson','Otero','Bork','Bork','Swor','Rae','Rae','Hope','Jung','Almquist','Barish','Fisher','Fisher','Richardson','Todd','Hutchinson','Barish','Fringer','Fringer','Todd','Shah','Berger','Linovitz','Pettengill','Ditkoff','Pettengill','Fadi','Richardson','Anderson','Rae'),
    ('Pettengill','Nguyen','Nguyen','Minnock','Minnock','Minnock','Nguyen','Filips','Filips','Nguyen','Hang','Hang','Hang','Anderson','Anderson','Anderson','Ortiz','Ortiz','Minnock','Pettengill','Pettengill','Hutchinson','Hutchinson','Hutchinson','Todd','Todd','Filips','Smark','Smark','Smark','Todd'),
    ('X','X','Keene','Keene','Keene','X','X','X','X','Kelly','Kelly','Sagar','X','X','X','X','Wloszczynski','Kelly','Kache','X','X','X','X','Newson','Newson','Newson','X','X','X','X','Bodes'),
    ('Nguyen','Walters','Gratson','Jung','Ziadeh','Gratson','Otero','Otero','Rae','Linovitz','Jung','Ditkoff','Barish','Almquist','Almquist','Richardson','Walters','Linovitz','Ditkoff','Turner','Bork','Rontal','Rontal','Walters','Linovitz','Ziadeh','Barish','Anderson','Fadi','Richardson','Jung'),
    ('X','X','Bukhsh','Kelly','Kelly','Berman','Berman','X','X','Bodes','Bodes','Kache','Kache','Sagar','X','X','Bukhsh','Elvis','Newson','Sagar','Robinson','X','X','Berman','Kache','Bodes','Kache','Kelly','X','X','Sagar'),
    ('Bahl','Johnson','Getzinger','Pettengill','Pettengill','Richardson','Joseph','Bork','Barish','Walters','Linovitz','Hope','Smark','Jung','Fisher','Fadi','Nguyen','Walters','Clark','Almquist','Otero','Bork','Shah','Minnock','Swor','Rae','Hang','Linovitz','Getzinger','Swor','Filips'),
    ('Kelly','Wloszczynski','Kache','Sagar','Robinson','Kelly','Sagar','Wloszczynski','Wloszczynski','Berman','Berman','Bodes','Bodes','Kache','Elvis','Elvis','Elvis','Berman','Bukhsh','Kache','Kache','Elvis','Elvis','Robinson','Berman','Kache','Bodes','Elvis','Sagar','Newson','Robinson'),
    ('Smark','Bahl','Clark','Getzinger','Anderson','Barish','Gratson','Joseph','Bork','Hutchinson','Walters','Smark','Hope','Linovitz','Getzinger','Jung','Pettengill','Otero','Richardson','Rae','Barish','Otero','Bork','Almquist','Hang','Ortiz','Rae','Berger','Pettengill','Getzinger','Fadi'),
    ('Hutchinson','Fringer','Rae','Anderson','Getzinger','Bahl','Clark','Turner','Joseph','Richardson','Filips','Filips','Filips','Gratson','Jung','Getzinger','Jung','Berger','Gratson','Richardson','Rae','Barish','Otero','Filips','Almquist','Hang','Hutchinson','Almquist','Berger','Linovitz','Anderson'),
    ('Wloszczynski','Kelly','Sagar','Kache','Sagar','Robinson','Elvis','Sagar','Sagar','Elvis','Elvis','Bukhsh','Kelly','Bodes','Keene','Keene','Robinson','Newson','Berman','Bukhsh','Berman','Robinson','Bukhsh','Elvis','Keene','Berman','Berman','Bodes','Wloszczynski','Kelly','Newson'),
    ('Levasseur','Levasseur','Menoch','Adams','Adams','Menoch','Menoch','Adams','Benjamin','Benjamin','Adams','Adams','Benjamin','Benjamin','Adams','Adams','Levasseur','Levasseur','Menoch','Menoch','Menoch','Menoch','Menoch','Levasseur','Adams','Levasseur','Benjamin','Benjamin','Benjamin','Benjamin','Menoch'),
    ('Berman','Berman','Berman','Elvis','Elvis','Elvis','Kache','Kache','Kache','Keene','Keene','Keene','Bukhsh','Bukhsh','Bukhsh','Newson','Newson','Wloszczynski','Kelly','Kelly','Bodes','Bodes','Bodes','Sagar','Sagar','Sagar','Kelly','Robinson','Robinson','Robinson','Wloszczynski'),
    ('X','X','Elvis','X','Kache','X','X','X','X','Robinson','Robinson','Elvis','X','X','X','X','Keene','Bodes','X','X','X','X','X','Bukhsh','Robinson','Wloszczynski','X','X','X','X','Kelly'),
    ('Ortiz','Hutchinson','Shah','Rae','Fisher','Fadi','Barish','Clark','Turner','Pettengill','Hutchinson','Hutchinson','Bork','Filips','Linovitz','Gratson','Getzinger','Filips','Anderson','Gratson','Johnson','Johnson','Rae','Getzinger','Walters','Bork','Ortiz','Clark','Almquist','Berger','Getzinger'),
    ('Fisher','Ortiz','Anderson','Joseph','Smark','Anderson','Hutchinson','Barish','Clark','Fadi','Todd','Getzinger','Bahl','Bork','Fadi','Linovitz','Gratson','Nguyen','Filips','Filips','Hang','Hang','Johnson','Richardson','Getzinger','Walters','Jung','Swor','Clark','Almquist','Otero'),
    ('Bodes','Bodes','Bodes','Bodes','Bodes','Bukhsh','Bukhsh','Newson','Newson','Newson','Newson','Newson','Berman','Berman','Sagar','Sagar','Sagar','Robinson','Robinson','Wloszczynski','Wloszczynski','Kelly','Kelly','Kelly','Elvis','Elvis','Keene','Keene','Kache','Kache','Kache'),
    ('Robinson','Robinson','X','X','X','X','X','Bukhsh','Bukhsh','X','X','X','X','X','Berman','Berman','X','X','X','X','X','Wloszczynski','Wloszczynski','X','X','X','X','X','Keene','Keene','X'),
    ('Felice','Felice','Rontal','Felice','Felice','Felice','Felice','Farrow','Rontal','Farrow','Fadi','McPeak','Joseph','Ngo','Ngo','Rhea','Ngo','Rhea','Farrow','Anderson','Felice','Felice','Felice','Johnson','Minnock','Rhea','McPeak','Rhea','Farrow','Felice','Rontal'),
    ('X','X','Felice','Rontal','X','X','X','X','X','Rontal','McPeak','X','X','X','X','X','Rhea','Ngo','X','X','X','X','X','Gratson','Richardson','X','X','X','X','X','Felice'),
    ('Rhea','Smark','Ortiz','McPeak','McPeak','McPeak','Farrow','Ngo','Farrow','McPeak','Rhea','Rhea','McPeak','McPeak','Rhea','Ngo','Farrow','Farrow','Rhea','Farrow','Farrow','Ngo','Ngo','Ngo','Rhea','McPeak','Rhea','McPeak','McPeak','Farrow','Farrow');
